version: '2'
services:
  # Adapted from the official Confluent example: https://github.com/confluentinc/kafka-images/blob/master/examples/kafka-single-node/docker-compose.yml
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Adapted from https://github.com/confluentinc/examples/blob/5.1.1-post/microservices-orders/docker-compose.yml
  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
      - kafka
    command: "bash -c 'cub kafka-ready -b kafka:29092 1 180 && \
                       kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic tasks && \
                       kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic data'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'beehive'
      MYSQL_USER: 'bee'
      MYSQL_PASSWORD: 'hive'
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  beecamel:
    build: bee-camel-routes/.
    image: beecamel
    ports:
      - 9093:9093
    volumes:
      - ./bee-camel-routes:/io
    depends_on:
      - kafka
      - mariadb

  beehive1:
    build: beehive-simulation/.
    image: beehive
    ports:
      - 9094:9094
    command: --beehive.id=1
    volumes:
      - ./beehive-simulation:/io
    depends_on:
      - kafka

  beehive2:
    image: beehive
    ports:
      - 9095:9095
    command: --beehive.id=2
    volumes:
      - ./beehive-simulation:/io
    depends_on:
      - kafka
